version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  joke_service:
    build:
      context: .
      dockerfile: joke_service/joke_service.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - postgres
    environment:
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: 'user'
      RABBITMQ_PASSWORD: 'password'
      RABBITMQ_JOKE_METADATA_QUEUE: 'joke_metadata_queue'

  queue_consumer:
    build:
      context: .
      dockerfile: queue_consumer/consumer.Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: joke_db
      RABBITMQ_HOST: 'rabbitmq'
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: 'user'
      RABBITMQ_PASSWORD: 'password'
      RABBITMQ_JOKE_METADATA_QUEUE: 'joke_metadata_queue'

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: joke_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data:
