services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" 
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  
  joke_service:
    build:
      context: .
      dockerfile: joke_service/joke_service.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  queue_consumer:
    build:
      context: .
      dockerfile: queue_consumer/consumer.Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - rabbitmq
